version: 0.0
os: linux
files:
  - source: index.php
    destination: /var/www/html/
  - source: get-index-meta-data.php
    destination: /var/www/html/
  - source: get-root-dir.php
    destination: /var/www/html/
  - source: menu.php
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

