#!/bin/bash
sudo amazon-linux-extras install php7.4 -y
sudo yum install -y httpd
sudo wget http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm 
sudo rpm -ivh mysql-community-release-el7-5.noarch.rpm
sudo yum update -y
sudo yum install mysql-server -y
sudo yum clean metadata 
sudo yum install -y php php-common php-pear 
sudo yum install -y php-{cgi,curl,mbstring,gd,mysqlnd,gettext,json,xml,fpm,intl,zip}  
cd /var/www/html
sudo chmod 777 index.php
sudo echo "<h1>Hello World from Plum Commerce Inc. <p> IP Address: ip-10-0-0-198.ap-northeast-2.compute.internal</p> <p>AZ: ap-northeast-2a </h1></p>" > index.php

