#!/bin/bash
systemctl start httpd.service
systemctl start mysqld.service
cd /var/www/html
sudo vi index.php
sudo chmod 777 index.php
sudo echo "<h1>Hello World from Plum Commerce Inc. <p> IP Address: ip-10-0-0-198.ap-northeast-2.compute.internal</p> <p>AZ: ap-northeast-2a </h1></p>" > index.php
